import { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { Orders } from './Orders';
import { getOrders } from '../utils/storage';
import { getProductById, getProducts } from '../data/products';
import {
  createApiProduct,
  deleteApiProduct,
  fetchApiProducts,
  scheduleVisibilityRefresh,
  updateApiProduct
} from '../services/productService';
import { apiUrl } from '../lib/api';
import {
  getCategoryThumbnailOverrides,
  getDefaultCategoryImage,
  HOMEPAGE_CATEGORY_SECTIONS_FOR_ADMIN,
  type CategoryThumbnailOverrides
} from '../data/homepageCategories';
import {
  hydrateSiteContentFromServer,
  persistAndSyncSiteContent,
  readSiteContentFromClient,
  type FlashDealCardConfig,
  type HomeBanner,
} from '../services/siteContentService';

type DashboardMode = 'orders' | 'group-cards' | 'homepage-banners' | 'flash-deals' | 'category-thumbnails';

const groupLabelByCategory: Record<string, string> = {
  'chips-namkeen': 'Snacks & Drinks',
  'sweets-chocolates': 'Snacks & Drinks',
  'drinks-juices': 'Snacks & Drinks',
  'tea-coffee': 'Snacks & Drinks',
  'instant-food': 'Snacks & Drinks',
  'sauces-spreads': 'Snacks & Drinks',
  'paan-corner': 'Snacks & Drinks',
  'ice-creams': 'Snacks & Drinks',
  'vegetables-fruits': 'Grocery & Kitchen',
  'atta-rice-dal': 'Grocery & Kitchen',
  'oil-ghee-masala': 'Grocery & Kitchen',
  'dairy-bread-eggs': 'Grocery & Kitchen',
  'bakery-biscuits': 'Grocery & Kitchen',
  'dry-fruits-cereals': 'Grocery & Kitchen',
  'chicken-meat-fish': 'Grocery & Kitchen',
  'kitchenware-appliances': 'Grocery & Kitchen',
  'kitchen-stock-up': 'Grocery & Kitchen',
  'bath-body': 'Beauty & Personal Care',
  'hair': 'Beauty & Personal Care',
  'skin-face': 'Beauty & Personal Care',
  'beauty-cosmetics': 'Beauty & Personal Care',
  'feminine-hygiene': 'Beauty & Personal Care',
  'baby-care': 'Beauty & Personal Care',
  'health-pharma': 'Beauty & Personal Care',
  'sexual-wellness': 'Beauty & Personal Care'
};

const categoryOptions = Object.keys(groupLabelByCategory);
const groupOptions = Array.from(new Set(Object.values(groupLabelByCategory)));
const unitOptions = ['pcs', 'g', 'kg', 'ml', 'l'];
const categoriesByGroup = groupOptions.reduce<Record<string, string[]>>((acc, group) => {
  acc[group] = categoryOptions.filter((category) => groupLabelByCategory[category] === group);
  return acc;
}, {});

const formatCategoryLabel = (category: string) => category.replace(/-/g, ' ').replace(/\b\w/g, (ch) => ch.toUpperCase());

const autoGenerateDescription = (name: string, group: string, category: string) => {
  const productName = name.trim() || 'This product';
  const categoryLabel = formatCategoryLabel(category || 'general category');
  const groupLabel = group || 'General Group';
  return `${productName} is a quality item in ${categoryLabel} under ${groupLabel}. Fresh stock and value pricing for everyday shopping.`;
};

interface GroupProductCard {
  productId: string;
  name: string;
  image: string;
  group: string;
  category: string;
  description: string;
  stock: number;
  price: number;
  unitValue: number;
  unit: string;
  quantitySold: number;
  orderCount: number;
  revenue: number;
}

const ADMIN_DASHBOARD_AUTH_KEY = 'admin_dashboard_authenticated';
// Removing hardcoded password, fetching from backend instead

const warnIfSiteSyncFailed = (saved: boolean) => {
  if (!saved) {
    toast.message('Saved on this device only — start the API server so all visitors see your changes.');
  }
};

const defaultHomeBanners: HomeBanner[] = [
  { id: 1, src: '/assets/images/Banner 1 .png', link: '/' },
  { id: 2, src: '/assets/images/Banner 2.png', link: '/' },
  { id: 3, src: '/assets/images/Banner 3.png', link: '/' },
  { id: 4, src: '/assets/images/Banner 4.png', link: '/' },
  { id: 5, src: '/assets/images/Banner 5.png', link: '/' },
  { id: 7, src: '/assets/images/Banner 7.png', link: '/' }
];

export function AdminOrderDashboard() {
  const [mode, setMode] = useState<DashboardMode>('orders');
  const [adminPasswordInput, setAdminPasswordInput] = useState('');
  const [adminPasswordError, setAdminPasswordError] = useState('');
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(() => {
    try {
      return sessionStorage.getItem(ADMIN_DASHBOARD_AUTH_KEY) === 'true';
    } catch {
      return false;
    }
  });
  const [cardEdits, setCardEdits] = useState<Record<string, Partial<GroupProductCard>>>(
    () => readSiteContentFromClient().productCardEdits as Record<string, Partial<GroupProductCard>>
  );
  const [editingCardId, setEditingCardId] = useState<string | null>(null);
  const [draftEdit, setDraftEdit] = useState<Partial<GroupProductCard>>({});
  const [catalogSyncVersion, setCatalogSyncVersion] = useState(0);
  const [isSavingProduct, setIsSavingProduct] = useState(false);

  useEffect(() => {
    const onProductsUpdated = () => setCatalogSyncVersion((v) => v + 1);
    window.addEventListener('productsUpdated', onProductsUpdated);
    return () => window.removeEventListener('productsUpdated', onProductsUpdated);
  }, []);

  useEffect(() => {
    const syncAdminStateFromClient = () => {
      const content = readSiteContentFromClient();
      setCardEdits(content.productCardEdits as Record<string, Partial<GroupProductCard>>);
      setCustomCards(content.customCards as GroupProductCard[]);
      setDeletedCardIds(content.deletedProductIds);
      setHomeBanners(content.homepageBanners.length ? content.homepageBanners : defaultHomeBanners);
      setFlashDealCards(content.flashDeals.cards);
      setFlashDealEndAt(content.flashDeals.endAt);
      setCategoryThumbnailOverrides(content.categoryThumbnails);
    };
    void hydrateSiteContentFromServer().then(syncAdminStateFromClient);
    window.addEventListener('siteContentUpdated', syncAdminStateFromClient);
    window.addEventListener('productsUpdated', syncAdminStateFromClient);
    return () => {
      window.removeEventListener('siteContentUpdated', syncAdminStateFromClient);
      window.removeEventListener('productsUpdated', syncAdminStateFromClient);
    };
  }, []);
  const [showAddForm, setShowAddForm] = useState(false);
  const [customCards, setCustomCards] = useState<GroupProductCard[]>(
    () => readSiteContentFromClient().customCards as GroupProductCard[]
  );
  const [deletedCardIds, setDeletedCardIds] = useState<string[]>(
    () => readSiteContentFromClient().deletedProductIds
  );
  const [homeBanners, setHomeBanners] = useState<HomeBanner[]>(() => {
    const remote = readSiteContentFromClient().homepageBanners;
    return remote.length ? remote : defaultHomeBanners;
  });
  const [newBannerSrc, setNewBannerSrc] = useState('');
  const [newBannerLink, setNewBannerLink] = useState('/');
  const [flashDealCards, setFlashDealCards] = useState<FlashDealCardConfig[]>(
    () => readSiteContentFromClient().flashDeals.cards
  );
  const [flashDealEndAt, setFlashDealEndAt] = useState<string>(
    () => readSiteContentFromClient().flashDeals.endAt
  );
  const [newFlashDealProductId, setNewFlashDealProductId] = useState('');
  const [newFlashDealBadgeText, setNewFlashDealBadgeText] = useState('Low Stock');
  const [editingFlashDealProductId, setEditingFlashDealProductId] = useState<string | null>(null);
  const [editingFlashDealNextProductId, setEditingFlashDealNextProductId] = useState('');
  const [editingFlashDealBadgeText, setEditingFlashDealBadgeText] = useState('Low Stock');
  const [categoryThumbnailOverrides, setCategoryThumbnailOverrides] = useState<CategoryThumbnailOverrides>(
    () => getCategoryThumbnailOverrides()
  );
  const [groupCardsFilterGroup, setGroupCardsFilterGroup] = useState('all');
  const [groupCardsFilterCategory, setGroupCardsFilterCategory] = useState('all');
  const [groupCardsSearch, setGroupCardsSearch] = useState('');
  const [addDraft, setAddDraft] = useState<Partial<GroupProductCard>>({
    name: '',
    image: '',
    group: 'Snacks & Drinks',
    category: 'chips-namkeen',
    description: '',
    stock: 0,
    price: 0,
    unitValue: 1,
    unit: 'pcs',
    quantitySold: 0,
    orderCount: 0,
    revenue: 0
  });

  const groupedCards = useMemo(() => {
    const orders = getOrders();
    const productStats = new Map<string, GroupProductCard>();

    orders.forEach((order) => {
      order.items.forEach((item) => {
        const product = getProductById(item.productId);
        if (!product) return;

        const existing = productStats.get(product.id);
        const lineRevenue = product.price * item.quantity;

        if (existing) {
          existing.quantitySold += item.quantity;
          existing.orderCount += 1;
          existing.revenue += lineRevenue;
          return;
        }

        productStats.set(product.id, {
          productId: product.id,
          name: product.name,
          image: product.image,
          group: groupLabelByCategory[product.category] || 'Other Categories',
          category: product.category,
          description: product.description,
          stock: product.stock,
          price: product.price,
          unitValue: 1,
          unit: 'pcs',
          quantitySold: item.quantity,
          orderCount: 1,
          revenue: lineRevenue
        });
      });
    });

    // Ensure dashboard shows more products by including catalog items
    // even if they have not been ordered yet.
    getProducts().forEach((product) => {
      if (productStats.has(product.id)) return;
      productStats.set(product.id, {
        productId: product.id,
        name: product.name,
        image: product.image,
        group: groupLabelByCategory[product.category] || 'Other Categories',
        category: product.category,
        description: product.description,
        stock: product.stock,
        price: product.price,
        unitValue: 1,
        unit: 'pcs',
        quantitySold: 0,
        orderCount: 0,
        revenue: 0
      });
    });

    customCards.forEach((custom) => {
      productStats.set(custom.productId, custom);
    });

    const grouped = Array.from(productStats.values())
      .filter((card) => !deletedCardIds.includes(card.productId))
      .map((card) => {
        const merged = { ...card, ...(cardEdits[card.productId] || {}) };
        return {
          ...merged,
          unit: typeof merged.unit === 'string' && merged.unit.trim() ? merged.unit : 'pcs',
          unitValue: typeof merged.unitValue === 'number' && Number.isFinite(merged.unitValue) ? merged.unitValue : 1
        };
      })
      .sort((a, b) => b.quantitySold - a.quantitySold || a.name.localeCompare(b.name));

    return grouped.reduce<Record<string, GroupProductCard[]>>((acc, card) => {
      if (!acc[card.group]) acc[card.group] = [];
      acc[card.group].push(card);
      return acc;
    }, {});
  }, [cardEdits, customCards, deletedCardIds, catalogSyncVersion]);

  const allProducts = useMemo(
    () =>
      getProducts().sort((a, b) => a.name.localeCompare(b.name)),
    [cardEdits, customCards, deletedCardIds, catalogSyncVersion]
  );

  const groupCardsCategoryOptions = useMemo(() => {
    if (groupCardsFilterGroup === 'all') return categoryOptions;
    return categoriesByGroup[groupCardsFilterGroup] || [];
  }, [groupCardsFilterGroup]);

  const filteredGroupedCards = useMemo(() => {
    const query = groupCardsSearch.trim().toLowerCase();
    return Object.entries(groupedCards).reduce<Record<string, GroupProductCard[]>>((acc, [groupName, cards]) => {
      if (groupCardsFilterGroup !== 'all' && groupName !== groupCardsFilterGroup) return acc;
      const nextCards = cards.filter((card) => {
        if (groupCardsFilterCategory !== 'all' && card.category !== groupCardsFilterCategory) return false;
        if (!query) return true;
        const haystack = `${card.name} ${card.category} ${card.description}`.toLowerCase();
        return haystack.includes(query);
      });
      if (nextCards.length > 0) acc[groupName] = nextCards;
      return acc;
    }, {});
  }, [groupedCards, groupCardsFilterGroup, groupCardsFilterCategory, groupCardsSearch]);

  const updateDraft = (key: keyof GroupProductCard, value: string) => {
    if (key === 'quantitySold' || key === 'orderCount' || key === 'revenue' || key === 'stock' || key === 'price' || key === 'unitValue') {
      const num = Number(value);
      setDraftEdit((prev) => ({ ...prev, [key]: Number.isFinite(num) ? num : 0 }));
      return;
    }
    if (key === 'group') {
      const nextCategories = categoriesByGroup[value] || [];
      const nextCategory = nextCategories[0] || '';
      setDraftEdit((prev) => ({ ...prev, group: value, category: nextCategory }));
      return;
    }
    setDraftEdit((prev) => ({ ...prev, [key]: value }));
  };

  const startEditing = (card: GroupProductCard) => {
    setEditingCardId(card.productId);
    setDraftEdit({ ...card });
  };

  const cancelEditing = () => {
    setEditingCardId(null);
    setDraftEdit({});
  };

  const saveEditing = async (productId: string) => {
    const isMongoId = /^[a-f\d]{24}$/i.test(productId);
    const customIndex = customCards.findIndex((card) => card.productId === productId);

    if (customIndex >= 0) {
      const updatedCard = {
        ...customCards[customIndex],
        ...draftEdit,
        productId
      } as GroupProductCard;
      const nextCustom = [...customCards];
      nextCustom[customIndex] = updatedCard;
      await persistCustomCards(nextCustom);

      if (isMongoId) {
        await updateApiProduct(productId, {
          name: updatedCard.name,
          description: updatedCard.description,
          price: updatedCard.price,
          category: updatedCard.category,
          group: updatedCard.group,
          image: updatedCard.image,
          stock: updatedCard.stock,
          unit: updatedCard.unit,
          unitValue: updatedCard.unitValue
        });
        void fetchApiProducts();
      }
    } else {
      const merged = { ...cardEdits[productId], ...draftEdit };
      const next = { ...cardEdits, [productId]: merged };
      setCardEdits(next);
      warnIfSiteSyncFailed(await persistAndSyncSiteContent({ productCardEdits: next }));

      if (isMongoId) {
        const base = getProductById(productId);
        await updateApiProduct(productId, {
          name: String(merged.name ?? base?.name ?? ''),
          description: String(merged.description ?? base?.description ?? ''),
          price: Number(merged.price ?? base?.price ?? 0),
          category: String(merged.category ?? base?.category ?? ''),
          group: String(merged.group ?? groupLabelByCategory[base?.category || ''] ?? ''),
          image: String(merged.image ?? base?.image ?? ''),
          stock: Number(merged.stock ?? base?.stock ?? 0),
          unit: String(merged.unit ?? 'pcs'),
          unitValue: Number(merged.unitValue ?? 1)
        });
        void fetchApiProducts();
      }
    }

    cancelEditing();
    toast.success(isMongoId ? 'Product updated for all visitors.' : 'Product card updated for all visitors.');
  };

  const persistCustomCards = async (next: GroupProductCard[]) => {
    setCustomCards(next);
    const saved = await persistAndSyncSiteContent({ customCards: next });
    warnIfSiteSyncFailed(saved);
  };

  const persistDeletedCardIds = async (next: string[]) => {
    setDeletedCardIds(next);
    const saved = await persistAndSyncSiteContent({ deletedProductIds: next });
    warnIfSiteSyncFailed(saved);
  };

  const handleDeleteCard = async (card: GroupProductCard) => {
    const confirmed = window.confirm(`Delete "${card.name}" from dashboard and website?`);
    if (!confirmed) return;

    const isMongoId = /^[a-f\d]{24}$/i.test(card.productId);

    if (isMongoId) {
      await deleteApiProduct(card.productId);
      const nextCustomCards = customCards.filter((item) => item.productId !== card.productId);
      await persistCustomCards(nextCustomCards);
      void fetchApiProducts();
    } else if (card.productId.startsWith('custom_')) {
      const nextCustomCards = customCards.filter((item) => item.productId !== card.productId);
      await persistCustomCards(nextCustomCards);
    } else if (!deletedCardIds.includes(card.productId)) {
      await persistDeletedCardIds([...deletedCardIds, card.productId]);
    }

    if (cardEdits[card.productId]) {
      const nextEdits = { ...cardEdits };
      delete nextEdits[card.productId];
      setCardEdits(nextEdits);
      warnIfSiteSyncFailed(await persistAndSyncSiteContent({ productCardEdits: nextEdits }));
    }

    if (editingCardId === card.productId) {
      cancelEditing();
    }
  };

  const processImageFile = (file: File | null, onReady: (dataUrl: string) => void) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const result = typeof reader.result === 'string' ? reader.result : '';
      if (!result) return;

      const img = new Image();
      img.onload = () => {
        const maxWidth = 480;
        const scale = Math.min(1, maxWidth / img.width);
        const canvas = document.createElement('canvas');
        canvas.width = Math.max(1, Math.round(img.width * scale));
        canvas.height = Math.max(1, Math.round(img.height * scale));
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          onReady(result);
          return;
        }
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
        const compressed = canvas.toDataURL('image/jpeg', 0.62);
        onReady(compressed);
      };
      img.src = result;
    };
    reader.readAsDataURL(file);
  };

  const handleImageUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setDraftEdit((prev) => ({ ...prev, image: dataUrl })));
  };

  const handleAddImageUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setAddDraft((prev) => ({ ...prev, image: dataUrl })));
  };
  const handleAddBannerUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setNewBannerSrc(dataUrl));
  };

  const persistHomeBanners = (next: HomeBanner[]) => {
    setHomeBanners(next);
    void persistAndSyncSiteContent({ homepageBanners: next }).then(warnIfSiteSyncFailed);
  };

  const handleAddBanner = () => {
    const src = newBannerSrc.trim();
    if (!src) return;
    const nextBanner: HomeBanner = {
      id: Date.now(),
      src,
      link: newBannerLink.trim() || '/'
    };
    persistHomeBanners([nextBanner, ...homeBanners]);
    setNewBannerSrc('');
    setNewBannerLink('/');
  };

  const handleReplaceBannerImage = (bannerId: number, src: string) => {
    const trimmed = src.trim();
    if (!trimmed) return;
    const next = homeBanners.map((banner) => (banner.id === bannerId ? { ...banner, src: trimmed } : banner));
    persistHomeBanners(next);
  };
  const handleReplaceBannerUpload = (bannerId: number, file: File | null) => {
    processImageFile(file, (dataUrl) => handleReplaceBannerImage(bannerId, dataUrl));
  };

  const handleReplaceBannerLink = (bannerId: number, link: string) => {
    const next = homeBanners.map((banner) => (banner.id === bannerId ? { ...banner, link: link.trim() || '/' } : banner));
    persistHomeBanners(next);
  };

  const handleDeleteBanner = (bannerId: number) => {
    const next = homeBanners.filter((banner) => banner.id !== bannerId);
    persistHomeBanners(next.length ? next : defaultHomeBanners);
  };

  const persistCategoryThumbnails = (next: CategoryThumbnailOverrides) => {
    setCategoryThumbnailOverrides(next);
    void persistAndSyncSiteContent({ categoryThumbnails: next }).then(warnIfSiteSyncFailed);
  };

  const handleCategoryThumbnailUrl = (categoryId: string, imageUrl: string) => {
    const trimmed = imageUrl.trim();
    if (!trimmed) return;
    persistCategoryThumbnails({ ...categoryThumbnailOverrides, [categoryId]: trimmed });
    toast.success('Category thumbnail updated');
  };

  const handleCategoryThumbnailUpload = (categoryId: string, file: File | null) => {
    processImageFile(file, (dataUrl) => handleCategoryThumbnailUrl(categoryId, dataUrl));
  };

  const handleResetCategoryThumbnail = (categoryId: string) => {
    const next = { ...categoryThumbnailOverrides };
    delete next[categoryId];
    persistCategoryThumbnails(next);
    toast.success('Reset to default thumbnail');
  };

  const getCategoryThumbnailPreview = (categoryId: string) => {
    const custom = categoryThumbnailOverrides[categoryId];
    if (typeof custom === 'string' && custom.trim()) return custom.trim();
    return getDefaultCategoryImage(categoryId);
  };

  const persistFlashDeals = (cards: FlashDealCardConfig[], endAt: string) => {
    setFlashDealCards(cards);
    setFlashDealEndAt(endAt);
    void persistAndSyncSiteContent({ flashDeals: { cards, endAt } }).then(warnIfSiteSyncFailed);
  };

  const handleAddFlashDealCard = () => {
    if (!newFlashDealProductId) return;
    if (flashDealCards.some((c) => c.productId === newFlashDealProductId)) return;
    const next = [
      ...flashDealCards,
      {
        productId: newFlashDealProductId,
        badgeText: newFlashDealBadgeText.trim() || 'Low Stock'
      }
    ];
    persistFlashDeals(next, flashDealEndAt);
    setNewFlashDealProductId('');
    setNewFlashDealBadgeText('Low Stock');
  };

  const handleRemoveFlashDealCard = (productId: string) => {
    const next = flashDealCards.filter((c) => c.productId !== productId);
    persistFlashDeals(next, flashDealEndAt);
  };

  const handleUpdateFlashBadgeText = (productId: string, badgeText: string) => {
    const next = flashDealCards.map((c) =>
      c.productId === productId ? { ...c, badgeText } : c
    );
    persistFlashDeals(next, flashDealEndAt);
  };

  const startEditFlashDealCard = (card: FlashDealCardConfig) => {
    setEditingFlashDealProductId(card.productId);
    setEditingFlashDealNextProductId(card.productId);
    setEditingFlashDealBadgeText(card.badgeText || 'Low Stock');
  };

  const cancelEditFlashDealCard = () => {
    setEditingFlashDealProductId(null);
    setEditingFlashDealNextProductId('');
    setEditingFlashDealBadgeText('Low Stock');
  };

  const saveEditFlashDealCard = () => {
    if (!editingFlashDealProductId || !editingFlashDealNextProductId) return;
    const duplicateExists =
      editingFlashDealNextProductId !== editingFlashDealProductId &&
      flashDealCards.some((c) => c.productId === editingFlashDealNextProductId);
    if (duplicateExists) return;
    const next = flashDealCards.map((c) =>
      c.productId === editingFlashDealProductId
        ? {
            productId: editingFlashDealNextProductId,
            badgeText: editingFlashDealBadgeText.trim() || 'Low Stock'
          }
        : c
    );
    persistFlashDeals(next, flashDealEndAt);
    cancelEditFlashDealCard();
  };

  const updateAddDraft = (key: keyof GroupProductCard, value: string) => {
    if (key === 'quantitySold' || key === 'orderCount' || key === 'revenue' || key === 'stock' || key === 'price' || key === 'unitValue') {
      const num = Number(value);
      setAddDraft((prev) => ({ ...prev, [key]: Number.isFinite(num) ? num : 0 }));
      return;
    }
    if (key === 'group') {
      const nextCategories = categoriesByGroup[value] || [];
      const nextCategory = nextCategories[0] || '';
      setAddDraft((prev) => ({
        ...prev,
        group: value,
        category: nextCategory,
        description: autoGenerateDescription(String(prev.name || ''), value, nextCategory)
      }));
      return;
    }
    if (key === 'name') {
      setAddDraft((prev) => ({
        ...prev,
        name: value,
        description: autoGenerateDescription(value, String(prev.group || ''), String(prev.category || ''))
      }));
      return;
    }
    if (key === 'category') {
      setAddDraft((prev) => ({
        ...prev,
        category: value,
        description: autoGenerateDescription(String(prev.name || ''), String(prev.group || ''), value)
      }));
      return;
    }
    setAddDraft((prev) => ({ ...prev, [key]: value }));
  };

  const handleAddCardSave = async () => {
    if (!addDraft.name || !addDraft.group || !addDraft.category) return;

    const newCard: GroupProductCard = {
      productId: `custom_${Date.now()}`,
      name: String(addDraft.name),
      image: String(addDraft.image || ''),
      group: String(addDraft.group),
      category: String(addDraft.category),
      description: String(addDraft.description || ''),
      stock: Number(addDraft.stock || 0),
      price: Number(addDraft.price || 0),
      unitValue: Number(addDraft.unitValue || 1),
      unit: String(addDraft.unit || 'pcs'),
      quantitySold: Number(addDraft.quantitySold || 0),
      orderCount: Number(addDraft.orderCount || 0),
      revenue: Number(addDraft.revenue || 0)
    };

    setIsSavingProduct(true);
    const result = await createApiProduct({
      name: newCard.name,
      description: newCard.description,
      price: newCard.price,
      category: newCard.category,
      group: newCard.group,
      image: newCard.image,
      stock: newCard.stock,
      unit: newCard.unit,
      unitValue: newCard.unitValue
    });
    setIsSavingProduct(false);

    if (!result.ok) {
      toast.error(result.error);
      return;
    }

    newCard.productId = result.product.id;
    await persistCustomCards([newCard, ...customCards]);
    scheduleVisibilityRefresh();
    void fetchApiProducts();
    toast.success('Product saved and synced — it will show on the website for all visitors.');
    setShowAddForm(false);
    setAddDraft({
      name: '',
      image: '',
      group: 'Snacks & Drinks',
      category: 'chips-namkeen',
      description: '',
      stock: 0,
      price: 0,
      unitValue: 1,
      unit: 'pcs',
      quantitySold: 0,
      orderCount: 0,
      revenue: 0
    });
  };

  const [isLoggingIn, setIsLoggingIn] = useState(false);

  const handleAdminLogin = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!adminPasswordInput) {
      setAdminPasswordError('Please enter a password.');
      return;
    }

    setIsLoggingIn(true);
    try {
      const response = await fetch(apiUrl('/api/auth/admin-login'), {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ password: adminPasswordInput }),
      });

      const data = await response.json();

      if (response.ok && data.success) {
        setIsAuthenticated(true);
        setAdminPasswordError('');
        setAdminPasswordInput('');
        try {
          sessionStorage.setItem(ADMIN_DASHBOARD_AUTH_KEY, 'true');
        } catch {
          // no-op
        }
      } else {
        setAdminPasswordError(data.message || 'Invalid password. Please try again.');
      }
    } catch (error) {
      console.error('Admin login error:', error);
      setAdminPasswordError('Failed to connect to the server.');
    } finally {
      setIsLoggingIn(false);
    }
  };

  const handleAdminLogout = () => {
    setIsAuthenticated(false);
    setAdminPasswordInput('');
    setAdminPasswordError('');
    try {
      sessionStorage.removeItem(ADMIN_DASHBOARD_AUTH_KEY);
    } catch {
      // no-op
    }
  };

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen max-w-full overflow-x-hidden bg-tawang-cream flex items-center justify-center px-3">
        <section className="w-full max-w-md bg-white rounded-xl shadow-md p-5 md:p-6">
          <h2 className="font-heading text-xl md:text-2xl font-semibold text-gray-900 mb-2">Admin Dashboard Login</h2>
          <p className="text-sm text-gray-600 mb-4">Enter password to access admin dashboard.</p>
          <form onSubmit={handleAdminLogin} className="space-y-3">
            <input
              type="password"
              value={adminPasswordInput}
              onChange={(e) => {
                setAdminPasswordInput(e.target.value);
                if (adminPasswordError) setAdminPasswordError('');
              }}
              className="w-full px-3 py-2 border rounded"
              placeholder="Enter admin password"
            />
            {adminPasswordError && <p className="text-sm text-red-600">{adminPasswordError}</p>}
            <button disabled={isLoggingIn} type="submit" className={`w-full px-4 py-2 ${isLoggingIn ? 'bg-gray-400' : 'bg-tawang-gold hover:bg-tawang-gold'} text-white/90 rounded`}>
              {isLoggingIn ? 'Verifying...' : 'Enter Dashboard'}
            </button>
          </form>
        </section>
      </div>
    );
  }

  return (
    <div className="min-h-screen max-w-full overflow-x-hidden bg-tawang-cream">
      <div className="w-full px-2 md:px-4 pt-4 md:pt-8">
        <div className="mb-4 md:mb-6 bg-white rounded-xl shadow-sm p-3 md:p-4 flex flex-wrap items-stretch gap-2">
          <div className="w-full flex items-center justify-between gap-3 mb-1">
            <button
              type="button"
              onClick={handleAdminLogout}
              className="w-auto px-4 py-2 rounded-lg text-sm md:text-base border border-red-600 text-red-700 hover:bg-red-50 transition-colors"
            >
              Logout
            </button>
          </div>
          <button
            type="button"
            onClick={() => setMode('orders')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'orders' ? 'bg-tawang-gold text-white/90' : 'bg-tawang-beige text-gray-700 hover:bg-gray-200'}`}
          >
            Orders Section
          </button>
          <button
            type="button"
            onClick={() => setMode('group-cards')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'group-cards' ? 'bg-tawang-gold text-white/90' : 'bg-tawang-beige text-gray-700 hover:bg-gray-200'}`}
          >
            Group-wise Product Cards
          </button>
          <button
            type="button"
            onClick={() => setMode('homepage-banners')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'homepage-banners' ? 'bg-tawang-gold text-white/90' : 'bg-tawang-beige text-gray-700 hover:bg-gray-200'}`}
          >
            Homepage Banners
          </button>
          <button
            type="button"
            onClick={() => setMode('flash-deals')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'flash-deals' ? 'bg-tawang-gold text-white/90' : 'bg-tawang-beige text-gray-700 hover:bg-gray-200'}`}
          >
            Flash Deals Section
          </button>
          <button
            type="button"
            onClick={() => setMode('category-thumbnails')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'category-thumbnails' ? 'bg-tawang-gold text-white/90' : 'bg-tawang-beige text-gray-700 hover:bg-gray-200'}`}
          >
            Category Thumbnails
          </button>
          {mode === 'group-cards' && (
            <button
              type="button"
              onClick={() => setShowAddForm((v) => !v)}
              className="w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base bg-tawang-navy text-white hover:bg-tawang-gold transition-colors"
            >
              {showAddForm ? 'Close Add Card' : 'Add Card'}
            </button>
          )}
        </div>

        {mode === 'orders' ? (
          <Orders />
        ) : (
          <div className="pb-8 md:pb-12 space-y-6">
            {mode === 'homepage-banners' && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="font-heading text-lg md:text-xl mb-4">Homepage Banners</h2>
                <p className="text-xs md:text-sm text-gray-600 mb-4">
                  Add a new banner or replace existing banner image/link. Changes reflect on website homepage banner section.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mb-4">
                  <input
                    value={newBannerSrc}
                    onChange={(e) => setNewBannerSrc(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="New banner image URL"
                  />
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => handleAddBannerUpload(e.target.files?.[0] || null)}
                    className="w-full px-3 py-2 border rounded bg-white"
                  />
                  <input
                    value={newBannerLink}
                    onChange={(e) => setNewBannerLink(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="Banner link (example: /category/chips-namkeen)"
                  />
                  <button type="button" onClick={handleAddBanner} className="px-4 py-2 bg-tawang-navy text-white rounded hover:bg-tawang-gold md:col-span-3">
                    Add Banner
                  </button>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {homeBanners.map((banner) => (
                    <div key={banner.id} className="border rounded-lg p-3 bg-tawang-beige">
                      <img src={banner.src} alt="Homepage banner" className="w-full h-28 object-cover rounded mb-2" />
                      <input
                        value={banner.src}
                        onChange={(e) => handleReplaceBannerImage(banner.id, e.target.value)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2"
                        placeholder="Replace banner image URL"
                      />
                      <input
                        type="file"
                        accept="image/*"
                        onChange={(e) => handleReplaceBannerUpload(banner.id, e.target.files?.[0] || null)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2 bg-white"
                      />
                      <input
                        value={banner.link}
                        onChange={(e) => handleReplaceBannerLink(banner.id, e.target.value)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2"
                        placeholder="Replace banner link"
                      />
                      <button
                        type="button"
                        onClick={() => handleDeleteBanner(banner.id)}
                        className="w-full px-2 py-1.5 text-xs md:text-sm border border-red-600 text-red-700 rounded hover:bg-red-50"
                      >
                        Delete Banner
                      </button>
                    </div>
                  ))}
                </div>
              </section>
            )}
            {mode === 'category-thumbnails' && (
              <section className="bg-white rounded-xl shadow-md p-3 md:p-4 space-y-5">
                <div>
                  <h2 className="font-heading text-base md:text-lg mb-1">Homepage Category Thumbnails</h2>
                  <p className="text-[11px] md:text-xs text-gray-600">
                    Upload or paste image URLs for Snacks &amp; Drinks, Grocery &amp; Kitchen, and Beauty &amp;
                    Personal Care category cards. Changes appear on the homepage immediately.
                  </p>
                </div>
                {HOMEPAGE_CATEGORY_SECTIONS_FOR_ADMIN.map((section) => (
                  <div key={section.id}>
                    <h3 className="font-heading text-sm md:text-base mb-2 text-tawang-navy">{section.title}</h3>
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-2">
                      {section.categories.map((category) => {
                        const previewSrc = getCategoryThumbnailPreview(category.id);
                        const hasCustom = Boolean(categoryThumbnailOverrides[category.id]?.trim());
                        return (
                          <article
                            key={category.id}
                            className="border rounded-md p-2 bg-tawang-beige flex flex-col min-w-0"
                          >
                            <img
                              src={previewSrc}
                              alt={category.name.replace('\n', ' ')}
                              className="w-full h-16 sm:h-[4.5rem] object-cover rounded border bg-white mb-1.5"
                            />
                            <p className="text-[11px] font-semibold text-gray-900 whitespace-pre-line leading-tight mb-0.5 line-clamp-2">
                              {category.name}
                            </p>
                            <p className="text-[9px] text-gray-500 mb-1 truncate" title={category.id}>
                              {category.id}
                            </p>
                            <input
                              defaultValue={categoryThumbnailOverrides[category.id] || ''}
                              key={`${category.id}-${hasCustom ? 'custom' : 'default'}`}
                              onBlur={(e) => {
                                const value = e.target.value.trim();
                                if (value) handleCategoryThumbnailUrl(category.id, value);
                              }}
                              onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                  e.currentTarget.blur();
                                }
                              }}
                              className="w-full px-1.5 py-1 border rounded text-[10px] mb-1 bg-white"
                              placeholder="Image URL"
                            />
                            <input
                              type="file"
                              accept="image/*"
                              onChange={(e) =>
                                handleCategoryThumbnailUpload(category.id, e.target.files?.[0] || null)
                              }
                              className="w-full text-[10px] mb-1 bg-white file:mr-1 file:py-0.5 file:px-1 file:rounded file:border-0 file:text-[9px] file:bg-tawang-navy file:text-white"
                            />
                            <button
                              type="button"
                              onClick={() => handleResetCategoryThumbnail(category.id)}
                              className="mt-auto w-full px-1.5 py-1 text-[10px] border border-gray-400 text-gray-700 rounded hover:bg-white"
                            >
                              Reset
                            </button>
                          </article>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </section>
            )}
            {mode === 'flash-deals' && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="font-heading text-lg md:text-xl mb-4">Flash Deals Section</h2>
                <p className="text-xs md:text-sm text-gray-600 mb-4">
                  Add or edit flash deal cards and set section end timing for homepage.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mb-3">
                  <select
                    value={newFlashDealProductId}
                    onChange={(e) => setNewFlashDealProductId(e.target.value)}
                    className="w-full px-3 py-2 border rounded bg-white"
                  >
                    <option value="">Select product for Flash Deal</option>
                    {allProducts.map((p) => (
                      <option key={p.id} value={p.id}>
                        {p.name} ({p.category})
                      </option>
                    ))}
                  </select>
                  <input
                    value={newFlashDealBadgeText}
                    onChange={(e) => setNewFlashDealBadgeText(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="Badge text (e.g. Low Stock)"
                  />
                  <button
                    type="button"
                    onClick={handleAddFlashDealCard}
                    className="px-4 py-2 bg-tawang-navy text-white rounded hover:bg-tawang-gold"
                  >
                    Add Flash Card
                  </button>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-4">
                  <label className="text-xs md:text-sm text-gray-700 font-medium">Deal End Time</label>
                  <input
                    type="datetime-local"
                    value={flashDealEndAt}
                    onChange={(e) => persistFlashDeals(flashDealCards, e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                  />
                </div>
                {flashDealCards.length === 0 ? (
                  <p className="text-xs md:text-sm text-gray-500">No flash deal cards added yet.</p>
                ) : (
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                    {flashDealCards.map((card) => {
                      const product = allProducts.find((p) => p.id === card.productId);
                      return (
                        <article key={card.productId} className="border rounded-lg p-3 bg-tawang-beige flex flex-col">
                          <img
                            src={product?.image || ''}
                            alt={product?.name || card.productId}
                            className="w-full h-32 rounded-md object-cover border bg-white mb-3"
                          />
                          <div className="min-w-0">
                            <p className="text-sm font-semibold text-gray-900 line-clamp-2">{product?.name || card.productId}</p>
                            <p className="text-xs text-gray-600 capitalize">{(product?.category || 'Unknown category').replace(/-/g, ' ')}</p>
                            <p className="text-xs text-gray-700 mb-2">Price: ₹{Number(product?.price || 0).toFixed(2)}</p>
                          </div>
                          {editingFlashDealProductId === card.productId ? (
                            <div className="grid grid-cols-1 gap-2 mt-auto">
                              <select
                                value={editingFlashDealNextProductId}
                                onChange={(e) => setEditingFlashDealNextProductId(e.target.value)}
                                className="w-full px-2 py-1.5 border rounded text-sm bg-white"
                              >
                                <option value="">Select product</option>
                                {allProducts.map((p) => (
                                  <option key={p.id} value={p.id}>
                                    {p.name} ({p.category})
                                  </option>
                                ))}
                              </select>
                              <input
                                value={editingFlashDealBadgeText}
                                onChange={(e) => setEditingFlashDealBadgeText(e.target.value)}
                                className="w-full px-2 py-1.5 border rounded text-sm"
                                placeholder="Badge text"
                              />
                              <div className="grid grid-cols-2 gap-2">
                                <button
                                  type="button"
                                  onClick={saveEditFlashDealCard}
                                  className="px-3 py-1.5 bg-tawang-gold text-tawang-navy rounded hover:bg-tawang-gold text-sm"
                                >
                                  Save
                                </button>
                                <button
                                  type="button"
                                  onClick={cancelEditFlashDealCard}
                                  className="px-3 py-1.5 border rounded hover:bg-tawang-beige text-sm"
                                >
                                  Cancel
                                </button>
                              </div>
                            </div>
                          ) : (
                            <div className="grid grid-cols-1 gap-2 mt-auto">
                              <input
                                value={card.badgeText}
                                onChange={(e) => handleUpdateFlashBadgeText(card.productId, e.target.value)}
                                className="w-full px-2 py-1.5 border rounded text-sm"
                                placeholder="Badge text"
                              />
                              <div className="grid grid-cols-2 gap-2">
                                <button
                                  type="button"
                                  onClick={() => startEditFlashDealCard(card)}
                                  className="px-3 py-1.5 border border-tawang-gold text-tawang-gold rounded hover:bg-tawang-beige text-sm"
                                >
                                  Edit
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleRemoveFlashDealCard(card.productId)}
                                  className="px-3 py-1.5 border border-red-600 text-red-700 rounded hover:bg-red-50 text-sm"
                                >
                                  Delete
                                </button>
                              </div>
                            </div>
                          )}
                        </article>
                      );
                    })}
                  </div>
                )}
              </section>
            )}
            {mode === 'group-cards' && showAddForm && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="font-heading text-lg md:text-xl mb-4">Add New Card</h2>
                <p className="text-xs md:text-sm text-gray-600 mb-4">
                  Fill product details below. This card will be added in the selected group and category section.
                </p>
                <div className="space-y-2">
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Product Name</label>
                  <input value={String(addDraft.name || '')} onChange={(e) => updateAddDraft('name', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Product Name" />
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Description</label>
                  <textarea value={String(addDraft.description || '')} onChange={(e) => updateAddDraft('description', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Description" rows={3} />
                  <button
                    type="button"
                    onClick={() =>
                      setAddDraft((prev) => ({
                        ...prev,
                        description: autoGenerateDescription(String(prev.name || ''), String(prev.group || ''), String(prev.category || ''))
                      }))
                    }
                    className="text-xs md:text-sm text-blue-700 hover:underline"
                  >
                    Auto Generate Description
                  </button>
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Upload Image</label>
                  <input type="file" accept="image/*" onChange={(e) => handleAddImageUpload(e.target.files?.[0] || null)} className="w-full px-3 py-2 border rounded bg-white" />
                  <p className="text-[11px] md:text-xs text-gray-500">Or paste image URL</p>
                  <input value={String(addDraft.image || '')} onChange={(e) => updateAddDraft('image', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Or paste image URL" />
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Group</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Category</label>
                    <select value={String(addDraft.group || '')} onChange={(e) => updateAddDraft('group', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {groupOptions.map((group) => (
                        <option key={group} value={group}>{group}</option>
                      ))}
                    </select>
                    <select value={String(addDraft.category || '')} onChange={(e) => updateAddDraft('category', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {(categoriesByGroup[String(addDraft.group || '')] || []).map((category) => (
                        <option key={category} value={category}>{category}</option>
                      ))}
                    </select>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Sold Qty</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Order Count</label>
                    <input type="number" value={String(addDraft.quantitySold || 0)} onChange={(e) => updateAddDraft('quantitySold', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Sold Qty" />
                    <input type="number" value={String(addDraft.orderCount || 0)} onChange={(e) => updateAddDraft('orderCount', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Order Count" />
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Price (₹)</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Stock</label>
                    <input type="number" step="0.01" value={String(addDraft.price || 0)} onChange={(e) => updateAddDraft('price', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Price (₹)" />
                    <input type="number" value={String(addDraft.stock || 0)} onChange={(e) => updateAddDraft('stock', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Stock" />
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit Value</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit</label>
                    <input type="number" min="0" step="0.01" value={String(addDraft.unitValue || 1)} onChange={(e) => updateAddDraft('unitValue', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="500" />
                    <select value={String(addDraft.unit || 'pcs')} onChange={(e) => updateAddDraft('unit', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {unitOptions.map((unit) => (
                        <option key={unit} value={unit}>{unit}</option>
                      ))}
                    </select>
                    <p className="text-[11px] md:text-xs text-gray-500 col-span-2">Preview: {String(addDraft.unitValue || 1)} {String(addDraft.unit || 'pcs')}</p>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700 col-span-2">Revenue (₹)</label>
                    <input type="number" step="0.01" value={String(addDraft.revenue || 0)} onChange={(e) => updateAddDraft('revenue', e.target.value)} className="w-full px-3 py-2 border rounded col-span-2" placeholder="Revenue (₹)" />
                  </div>
                  <button
                    type="button"
                    onClick={handleAddCardSave}
                    disabled={isSavingProduct}
                    className="px-4 py-2 bg-tawang-gold text-white/90 rounded hover:bg-tawang-gold disabled:opacity-60 disabled:cursor-not-allowed"
                  >
                    {isSavingProduct ? 'Saving…' : 'Save New Card'}
                  </button>
                </div>
              </section>
            )}
            {mode === 'group-cards' && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="font-heading text-lg md:text-xl mb-4">Filter Group-wise Cards</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                  <select
                    value={groupCardsFilterGroup}
                    onChange={(e) => {
                      const nextGroup = e.target.value;
                      setGroupCardsFilterGroup(nextGroup);
                      const allowedCategories = nextGroup === 'all' ? categoryOptions : categoriesByGroup[nextGroup] || [];
                      if (groupCardsFilterCategory !== 'all' && !allowedCategories.includes(groupCardsFilterCategory)) {
                        setGroupCardsFilterCategory('all');
                      }
                    }}
                    className="w-full px-3 py-2 border rounded bg-white"
                  >
                    <option value="all">All Groups</option>
                    {groupOptions.map((group) => (
                      <option key={group} value={group}>
                        {group}
                      </option>
                    ))}
                  </select>
                  <select
                    value={groupCardsFilterCategory}
                    onChange={(e) => setGroupCardsFilterCategory(e.target.value)}
                    className="w-full px-3 py-2 border rounded bg-white"
                  >
                    <option value="all">All Categories</option>
                    {groupCardsCategoryOptions.map((category) => (
                      <option key={category} value={category}>
                        {formatCategoryLabel(category)}
                      </option>
                    ))}
                  </select>
                  <input
                    value={groupCardsSearch}
                    onChange={(e) => setGroupCardsSearch(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="Search by product name/category"
                  />
                </div>
              </section>
            )}
            {mode === 'group-cards' && (Object.keys(groupedCards).length === 0 ? (
              <div className="bg-white rounded-xl shadow-md p-8 text-center text-gray-600">
                No products found from orders yet.
              </div>
            ) : Object.keys(filteredGroupedCards).length === 0 ? (
              <div className="bg-white rounded-xl shadow-md p-8 text-center text-gray-600">
                No cards match the selected filter or search.
              </div>
            ) : (
              Object.entries(filteredGroupedCards).map(([groupName, cards]) => (
                <section key={groupName} className="bg-white rounded-xl shadow-md p-4 md:p-6">
                  <h2 className="font-heading text-lg md:text-2xl mb-4">{groupName}</h2>
                  {Object.entries(
                    cards.reduce<Record<string, GroupProductCard[]>>((acc, card) => {
                      if (!acc[card.category]) acc[card.category] = [];
                      acc[card.category].push(card);
                      return acc;
                    }, {})
                  ).map(([categoryName, categoryCards]) => (
                    <div key={categoryName} className="mb-5 last:mb-0">
                      <h3 className="font-heading text-sm md:text-lg mb-3 capitalize text-gray-800">
                        {categoryName.replace(/-/g, ' ')}
                      </h3>
                      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        {categoryCards.map((card) => (
                          <article key={card.productId} className="border rounded-lg p-3 bg-tawang-beige">
                            <img
                              src={editingCardId === card.productId && draftEdit.image ? String(draftEdit.image) : card.image}
                              alt={card.name}
                              className="w-full h-32 object-cover rounded-md mb-3"
                            />
                            <h4 className="font-heading text-sm md:text-base mb-2 line-clamp-2">{card.name}</h4>
                            <div className="text-xs md:text-sm text-gray-700 space-y-1">
                              <p><strong>Sold Qty:</strong> {card.quantitySold}</p>
                              <p><strong>Order Count:</strong> {card.orderCount}</p>
                              <p><strong>Price:</strong> ₹{card.price.toFixed(2)}</p>
                              <p><strong>Stock:</strong> {card.stock}</p>
                              <p><strong>Unit:</strong> {card.unitValue ?? 1} {card.unit || 'pcs'}</p>
                              <p><strong>Revenue:</strong> ₹{card.revenue.toFixed(2)}</p>
                            </div>
                            {editingCardId === card.productId ? (
                              <div className="mt-3 border-t pt-3 space-y-2">
                                <p className="text-[11px] md:text-xs text-gray-500">
                                  Edit product details below. You can upload image from your device.
                                </p>
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Product Name</label>
                                <input
                                  value={String(draftEdit.name ?? '')}
                                  onChange={(e) => updateDraft('name', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Product name"
                                />
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Description</label>
                                <textarea
                                  value={String(draftEdit.description ?? '')}
                                  onChange={(e) => updateDraft('description', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Product description"
                                  rows={3}
                                />
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Upload Image</label>
                                <input
                                  type="file"
                                  accept="image/*"
                                  onChange={(e) => handleImageUpload(e.target.files?.[0] || null)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                />
                                <p className="text-[11px] md:text-xs text-gray-500">Or paste an image URL</p>
                                <input
                                  value={String(draftEdit.image ?? '')}
                                  onChange={(e) => updateDraft('image', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Image URL (add/change image)"
                                />
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Group</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Category</label>
                                  <select
                                    value={String(draftEdit.group ?? '')}
                                    onChange={(e) => updateDraft('group', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {groupOptions.map((group) => (
                                      <option key={group} value={group}>{group}</option>
                                    ))}
                                  </select>
                                  <select
                                    value={String(draftEdit.category ?? '')}
                                    onChange={(e) => updateDraft('category', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {(categoriesByGroup[String(draftEdit.group ?? '')] || []).map((category) => (
                                      <option key={category} value={category}>{category}</option>
                                    ))}
                                  </select>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Sold Qty</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Order Count</label>
                                  <input
                                    type="number"
                                    value={String(draftEdit.quantitySold ?? 0)}
                                    onChange={(e) => updateDraft('quantitySold', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Sold Qty"
                                  />
                                  <input
                                    type="number"
                                    value={String(draftEdit.orderCount ?? 0)}
                                    onChange={(e) => updateDraft('orderCount', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Order Count"
                                  />
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Price (₹)</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Stock</label>
                                  <input
                                    type="number"
                                    step="0.01"
                                    value={String(draftEdit.price ?? 0)}
                                    onChange={(e) => updateDraft('price', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Price"
                                  />
                                  <input
                                    type="number"
                                    value={String(draftEdit.stock ?? 0)}
                                    onChange={(e) => updateDraft('stock', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Stock"
                                  />
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit Value</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit</label>
                                  <input
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={String(draftEdit.unitValue ?? 1)}
                                    onChange={(e) => updateDraft('unitValue', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="500"
                                  />
                                  <select
                                    value={String(draftEdit.unit ?? 'pcs')}
                                    onChange={(e) => updateDraft('unit', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {unitOptions.map((unit) => (
                                      <option key={unit} value={unit}>{unit}</option>
                                    ))}
                                  </select>
                                  <p className="text-[11px] md:text-xs text-gray-500 col-span-2">Preview: {String(draftEdit.unitValue ?? 1)} {String(draftEdit.unit ?? 'pcs')}</p>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700 col-span-2">Revenue (₹)</label>
                                  <input
                                    type="number"
                                    step="0.01"
                                    value={String(draftEdit.revenue ?? 0)}
                                    onChange={(e) => updateDraft('revenue', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm col-span-2"
                                    placeholder="Revenue"
                                  />
                                </div>
                                <div className="flex flex-col sm:flex-row gap-2">
                                  <button
                                    type="button"
                                    onClick={() => saveEditing(card.productId)}
                                    className="flex-1 px-2 py-1.5 text-xs md:text-sm bg-tawang-gold text-white/90 rounded hover:bg-tawang-gold"
                                  >
                                    Save
                                  </button>
                                  <button
                                    type="button"
                                    onClick={cancelEditing}
                                    className="flex-1 px-2 py-1.5 text-xs md:text-sm border rounded hover:bg-tawang-beige"
                                  >
                                    Cancel
                                  </button>
                                </div>
                              </div>
                            ) : (
                              <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-2">
                                <button
                                  type="button"
                                  onClick={() => startEditing(card)}
                                  className="w-full px-2 py-1.5 text-xs md:text-sm border border-tawang-gold text-tawang-gold rounded hover:bg-tawang-beige"
                                >
                                  Edit Card
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleDeleteCard(card)}
                                  className="w-full px-2 py-1.5 text-xs md:text-sm border border-red-600 text-red-700 rounded hover:bg-red-50"
                                >
                                  Delete Card
                                </button>
                              </div>
                            )}
                          </article>
                        ))}
                      </div>
                    </div>
                  ))}
                </section>
              ))
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
