import { useMemo, useState } from 'react';
import { Orders } from './Orders';
import { getOrders } from '../utils/storage';
import { getProductById, getProducts } from '../data/products';

type DashboardMode = 'orders' | 'group-cards' | 'homepage-banners';

const groupLabelByCategory: Record<string, string> = {
  'chips-namkeen': 'Snacks & Drinks',
  'sweets-chocolates': 'Snacks & Drinks',
  'drinks-juices': 'Snacks & Drinks',
  'tea-coffee': 'Snacks & Drinks',
  'instant-food': 'Snacks & Drinks',
  'sauces-spreads': 'Snacks & Drinks',
  'paan-corner': 'Snacks & Drinks',
  'ice-creams': 'Snacks & Drinks',
  'vegetables-fruits': 'Grocery & Kitchen',
  'atta-rice-dal': 'Grocery & Kitchen',
  'oil-ghee-masala': 'Grocery & Kitchen',
  'dairy-bread-eggs': 'Grocery & Kitchen',
  'bakery-biscuits': 'Grocery & Kitchen',
  'dry-fruits-cereals': 'Grocery & Kitchen',
  'chicken-meat-fish': 'Grocery & Kitchen',
  'kitchenware-appliances': 'Grocery & Kitchen',
  'bath-body': 'Beauty & Personal Care',
  'hair': 'Beauty & Personal Care',
  'skin-face': 'Beauty & Personal Care',
  'beauty-cosmetics': 'Beauty & Personal Care',
  'feminine-hygiene': 'Beauty & Personal Care',
  'baby-care': 'Beauty & Personal Care',
  'health-pharma': 'Beauty & Personal Care',
  'sexual-wellness': 'Beauty & Personal Care'
};

const categoryOptions = Object.keys(groupLabelByCategory);
const groupOptions = Array.from(new Set(Object.values(groupLabelByCategory)));
const unitOptions = ['pcs', 'g', 'kg', 'ml', 'l'];
const categoriesByGroup = groupOptions.reduce<Record<string, string[]>>((acc, group) => {
  acc[group] = categoryOptions.filter((category) => groupLabelByCategory[category] === group);
  return acc;
}, {});

const formatCategoryLabel = (category: string) => category.replace(/-/g, ' ').replace(/\b\w/g, (ch) => ch.toUpperCase());

const autoGenerateDescription = (name: string, group: string, category: string) => {
  const productName = name.trim() || 'This product';
  const categoryLabel = formatCategoryLabel(category || 'general category');
  const groupLabel = group || 'General Group';
  return `${productName} is a quality item in ${categoryLabel} under ${groupLabel}. Fresh stock and value pricing for everyday shopping.`;
};

interface GroupProductCard {
  productId: string;
  name: string;
  image: string;
  group: string;
  category: string;
  description: string;
  stock: number;
  price: number;
  unitValue: number;
  unit: string;
  quantitySold: number;
  orderCount: number;
  revenue: number;
}

const ADMIN_CARD_EDITS_KEY = 'admin_dashboard_card_edits';
const ADMIN_CUSTOM_CARDS_KEY = 'admin_dashboard_custom_cards';
const ADMIN_DELETED_CARDS_KEY = 'admin_dashboard_deleted_cards';
const ADMIN_HOMEPAGE_BANNERS_KEY = 'admin_homepage_banners';

interface HomeBanner {
  id: number;
  src: string;
  link: string;
}

const defaultHomeBanners: HomeBanner[] = [
  { id: 1, src: '/assets/images/Banner 1 .png', link: '/' },
  { id: 2, src: '/assets/images/Banner 2.png', link: '/' },
  { id: 3, src: '/assets/images/Banner 3.png', link: '/' },
  { id: 4, src: '/assets/images/Banner 4.png', link: '/' },
  { id: 5, src: '/assets/images/Banner 5.png', link: '/' },
  { id: 7, src: '/assets/images/Banner 7.png', link: '/' }
];

export function AdminOrderDashboard() {
  const [mode, setMode] = useState<DashboardMode>('orders');
  const [cardEdits, setCardEdits] = useState<Record<string, Partial<GroupProductCard>>>(() => {
    try {
      const raw = localStorage.getItem(ADMIN_CARD_EDITS_KEY);
      return raw ? JSON.parse(raw) : {};
    } catch {
      return {};
    }
  });
  const [editingCardId, setEditingCardId] = useState<string | null>(null);
  const [draftEdit, setDraftEdit] = useState<Partial<GroupProductCard>>({});
  const [showAddForm, setShowAddForm] = useState(false);
  const [customCards, setCustomCards] = useState<GroupProductCard[]>(() => {
    try {
      const raw = localStorage.getItem(ADMIN_CUSTOM_CARDS_KEY);
      return raw ? JSON.parse(raw) : [];
    } catch {
      return [];
    }
  });
  const [deletedCardIds, setDeletedCardIds] = useState<string[]>(() => {
    try {
      const raw = localStorage.getItem(ADMIN_DELETED_CARDS_KEY);
      const parsed = raw ? JSON.parse(raw) : [];
      return Array.isArray(parsed) ? parsed.filter((id) => typeof id === 'string') : [];
    } catch {
      return [];
    }
  });
  const [homeBanners, setHomeBanners] = useState<HomeBanner[]>(() => {
    try {
      const raw = localStorage.getItem(ADMIN_HOMEPAGE_BANNERS_KEY);
      const parsed = raw ? JSON.parse(raw) : [];
      if (!Array.isArray(parsed) || parsed.length === 0) return defaultHomeBanners;
      return parsed
        .filter((item) => item && typeof item === 'object')
        .map((item, idx) => ({
          id: typeof item.id === 'number' ? item.id : Date.now() + idx,
          src: typeof item.src === 'string' ? item.src : '',
          link: typeof item.link === 'string' && item.link.trim() ? item.link : '/'
        }))
        .filter((banner) => banner.src.trim());
    } catch {
      return defaultHomeBanners;
    }
  });
  const [newBannerSrc, setNewBannerSrc] = useState('');
  const [newBannerLink, setNewBannerLink] = useState('/');
  const [addDraft, setAddDraft] = useState<Partial<GroupProductCard>>({
    name: '',
    image: '',
    group: 'Snacks & Drinks',
    category: 'chips-namkeen',
    description: '',
    stock: 0,
    price: 0,
    unitValue: 1,
    unit: 'pcs',
    quantitySold: 0,
    orderCount: 0,
    revenue: 0
  });

  const groupedCards = useMemo(() => {
    const orders = getOrders();
    const productStats = new Map<string, GroupProductCard>();

    orders.forEach((order) => {
      order.items.forEach((item) => {
        const product = getProductById(item.productId);
        if (!product) return;

        const existing = productStats.get(product.id);
        const lineRevenue = product.price * item.quantity;

        if (existing) {
          existing.quantitySold += item.quantity;
          existing.orderCount += 1;
          existing.revenue += lineRevenue;
          return;
        }

        productStats.set(product.id, {
          productId: product.id,
          name: product.name,
          image: product.image,
          group: groupLabelByCategory[product.category] || 'Other Categories',
          category: product.category,
          description: product.description,
          stock: product.stock,
          price: product.price,
          unitValue: 1,
          unit: 'pcs',
          quantitySold: item.quantity,
          orderCount: 1,
          revenue: lineRevenue
        });
      });
    });

    // Ensure dashboard shows more products by including catalog items
    // even if they have not been ordered yet.
    getProducts().forEach((product) => {
      if (productStats.has(product.id)) return;
      productStats.set(product.id, {
        productId: product.id,
        name: product.name,
        image: product.image,
        group: groupLabelByCategory[product.category] || 'Other Categories',
        category: product.category,
        description: product.description,
        stock: product.stock,
        price: product.price,
        unitValue: 1,
        unit: 'pcs',
        quantitySold: 0,
        orderCount: 0,
        revenue: 0
      });
    });

    customCards.forEach((custom) => {
      productStats.set(custom.productId, custom);
    });

    const grouped = Array.from(productStats.values())
      .filter((card) => !deletedCardIds.includes(card.productId))
      .map((card) => {
        const merged = { ...card, ...(cardEdits[card.productId] || {}) };
        return {
          ...merged,
          unit: typeof merged.unit === 'string' && merged.unit.trim() ? merged.unit : 'pcs',
          unitValue: typeof merged.unitValue === 'number' && Number.isFinite(merged.unitValue) ? merged.unitValue : 1
        };
      })
      .sort((a, b) => b.quantitySold - a.quantitySold || a.name.localeCompare(b.name));

    return grouped.reduce<Record<string, GroupProductCard[]>>((acc, card) => {
      if (!acc[card.group]) acc[card.group] = [];
      acc[card.group].push(card);
      return acc;
    }, {});
  }, [cardEdits, customCards, deletedCardIds]);

  const updateDraft = (key: keyof GroupProductCard, value: string) => {
    if (key === 'quantitySold' || key === 'orderCount' || key === 'revenue' || key === 'stock' || key === 'price' || key === 'unitValue') {
      const num = Number(value);
      setDraftEdit((prev) => ({ ...prev, [key]: Number.isFinite(num) ? num : 0 }));
      return;
    }
    if (key === 'group') {
      const nextCategories = categoriesByGroup[value] || [];
      const nextCategory = nextCategories[0] || '';
      setDraftEdit((prev) => ({ ...prev, group: value, category: nextCategory }));
      return;
    }
    setDraftEdit((prev) => ({ ...prev, [key]: value }));
  };

  const startEditing = (card: GroupProductCard) => {
    setEditingCardId(card.productId);
    setDraftEdit({ ...card });
  };

  const cancelEditing = () => {
    setEditingCardId(null);
    setDraftEdit({});
  };

  const saveEditing = (productId: string) => {
    const next = { ...cardEdits, [productId]: draftEdit };
    setCardEdits(next);
    (window as any).__ADMIN_PRODUCT_OVERRIDES__ = next;
    try {
      localStorage.setItem(ADMIN_CARD_EDITS_KEY, JSON.stringify(next));
    } catch {
      // Keep runtime override even if localStorage quota is exceeded.
      // This still reflects changes across website in current session.
    }
    window.dispatchEvent(new Event('productsUpdated'));
    cancelEditing();
  };

  const persistCustomCards = (next: GroupProductCard[]) => {
    setCustomCards(next);
    (window as any).__ADMIN_CUSTOM_CARDS__ = next;
    try {
      localStorage.setItem(ADMIN_CUSTOM_CARDS_KEY, JSON.stringify(next));
    } catch {
      // no-op
    }
    window.dispatchEvent(new Event('productsUpdated'));
  };

  const persistDeletedCardIds = (next: string[]) => {
    setDeletedCardIds(next);
    (window as any).__ADMIN_DELETED_PRODUCT_IDS__ = next;
    try {
      localStorage.setItem(ADMIN_DELETED_CARDS_KEY, JSON.stringify(next));
    } catch {
      // no-op
    }
    window.dispatchEvent(new Event('productsUpdated'));
  };

  const handleDeleteCard = (card: GroupProductCard) => {
    const confirmed = window.confirm(`Delete "${card.name}" from dashboard and website?`);
    if (!confirmed) return;

    if (card.productId.startsWith('custom_')) {
      const nextCustomCards = customCards.filter((item) => item.productId !== card.productId);
      persistCustomCards(nextCustomCards);
    } else if (!deletedCardIds.includes(card.productId)) {
      persistDeletedCardIds([...deletedCardIds, card.productId]);
    }

    if (cardEdits[card.productId]) {
      const nextEdits = { ...cardEdits };
      delete nextEdits[card.productId];
      setCardEdits(nextEdits);
      (window as any).__ADMIN_PRODUCT_OVERRIDES__ = nextEdits;
      try {
        localStorage.setItem(ADMIN_CARD_EDITS_KEY, JSON.stringify(nextEdits));
      } catch {
        // no-op
      }
    }

    if (editingCardId === card.productId) {
      cancelEditing();
    }
    window.dispatchEvent(new Event('productsUpdated'));
  };

  const processImageFile = (file: File | null, onReady: (dataUrl: string) => void) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const result = typeof reader.result === 'string' ? reader.result : '';
      if (!result) return;

      const img = new Image();
      img.onload = () => {
        const maxWidth = 640;
        const scale = Math.min(1, maxWidth / img.width);
        const canvas = document.createElement('canvas');
        canvas.width = Math.max(1, Math.round(img.width * scale));
        canvas.height = Math.max(1, Math.round(img.height * scale));
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          onReady(result);
          return;
        }
        ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
        const compressed = canvas.toDataURL('image/jpeg', 0.72);
        onReady(compressed);
      };
      img.src = result;
    };
    reader.readAsDataURL(file);
  };

  const handleImageUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setDraftEdit((prev) => ({ ...prev, image: dataUrl })));
  };

  const handleAddImageUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setAddDraft((prev) => ({ ...prev, image: dataUrl })));
  };
  const handleAddBannerUpload = (file: File | null) => {
    processImageFile(file, (dataUrl) => setNewBannerSrc(dataUrl));
  };

  const persistHomeBanners = (next: HomeBanner[]) => {
    setHomeBanners(next);
    (window as any).__ADMIN_HOMEPAGE_BANNERS__ = next;
    try {
      localStorage.setItem(ADMIN_HOMEPAGE_BANNERS_KEY, JSON.stringify(next));
    } catch {
      // no-op
    }
    window.dispatchEvent(new Event('productsUpdated'));
  };

  const handleAddBanner = () => {
    const src = newBannerSrc.trim();
    if (!src) return;
    const nextBanner: HomeBanner = {
      id: Date.now(),
      src,
      link: newBannerLink.trim() || '/'
    };
    persistHomeBanners([nextBanner, ...homeBanners]);
    setNewBannerSrc('');
    setNewBannerLink('/');
  };

  const handleReplaceBannerImage = (bannerId: number, src: string) => {
    const trimmed = src.trim();
    if (!trimmed) return;
    const next = homeBanners.map((banner) => (banner.id === bannerId ? { ...banner, src: trimmed } : banner));
    persistHomeBanners(next);
  };
  const handleReplaceBannerUpload = (bannerId: number, file: File | null) => {
    processImageFile(file, (dataUrl) => handleReplaceBannerImage(bannerId, dataUrl));
  };

  const handleReplaceBannerLink = (bannerId: number, link: string) => {
    const next = homeBanners.map((banner) => (banner.id === bannerId ? { ...banner, link: link.trim() || '/' } : banner));
    persistHomeBanners(next);
  };

  const handleDeleteBanner = (bannerId: number) => {
    const next = homeBanners.filter((banner) => banner.id !== bannerId);
    persistHomeBanners(next.length ? next : defaultHomeBanners);
  };

  const updateAddDraft = (key: keyof GroupProductCard, value: string) => {
    if (key === 'quantitySold' || key === 'orderCount' || key === 'revenue' || key === 'stock' || key === 'price' || key === 'unitValue') {
      const num = Number(value);
      setAddDraft((prev) => ({ ...prev, [key]: Number.isFinite(num) ? num : 0 }));
      return;
    }
    if (key === 'group') {
      const nextCategories = categoriesByGroup[value] || [];
      const nextCategory = nextCategories[0] || '';
      setAddDraft((prev) => ({
        ...prev,
        group: value,
        category: nextCategory,
        description: autoGenerateDescription(String(prev.name || ''), value, nextCategory)
      }));
      return;
    }
    if (key === 'name') {
      setAddDraft((prev) => ({
        ...prev,
        name: value,
        description: autoGenerateDescription(value, String(prev.group || ''), String(prev.category || ''))
      }));
      return;
    }
    if (key === 'category') {
      setAddDraft((prev) => ({
        ...prev,
        category: value,
        description: autoGenerateDescription(String(prev.name || ''), String(prev.group || ''), value)
      }));
      return;
    }
    setAddDraft((prev) => ({ ...prev, [key]: value }));
  };

  const handleAddCardSave = () => {
    if (!addDraft.name || !addDraft.group || !addDraft.category) return;
    const newCard: GroupProductCard = {
      productId: `custom_${Date.now()}`,
      name: String(addDraft.name),
      image: String(addDraft.image || ''),
      group: String(addDraft.group),
      category: String(addDraft.category),
      description: String(addDraft.description || ''),
      stock: Number(addDraft.stock || 0),
      price: Number(addDraft.price || 0),
      unitValue: Number(addDraft.unitValue || 1),
      unit: String(addDraft.unit || 'pcs'),
      quantitySold: Number(addDraft.quantitySold || 0),
      orderCount: Number(addDraft.orderCount || 0),
      revenue: Number(addDraft.revenue || 0)
    };
    persistCustomCards([newCard, ...customCards]);
    setShowAddForm(false);
    setAddDraft({
      name: '',
      image: '',
      group: 'Snacks & Drinks',
      category: 'chips-namkeen',
      description: '',
      stock: 0,
      price: 0,
      unitValue: 1,
      unit: 'pcs',
      quantitySold: 0,
      orderCount: 0,
      revenue: 0
    });
  };

  return (
    <div className="min-h-screen bg-yellow-50/40">
      <div className="w-full px-2 md:px-4 pt-4 md:pt-8">
        <div className="mb-4 md:mb-6 bg-white rounded-xl shadow-sm p-3 md:p-4 flex flex-wrap items-stretch gap-2">
          <button
            type="button"
            onClick={() => setMode('orders')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'orders' ? 'bg-green-600 text-yellow-100' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}
          >
            Orders Section
          </button>
          <button
            type="button"
            onClick={() => setMode('group-cards')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'group-cards' ? 'bg-green-600 text-yellow-100' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}
          >
            Group-wise Product Cards
          </button>
          <button
            type="button"
            onClick={() => setMode('homepage-banners')}
            className={`w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base transition-colors ${mode === 'homepage-banners' ? 'bg-green-600 text-yellow-100' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}
          >
            Homepage Banners
          </button>
          {mode === 'group-cards' && (
            <button
              type="button"
              onClick={() => setShowAddForm((v) => !v)}
              className="w-full sm:w-auto px-4 py-2 rounded-lg text-sm md:text-base bg-blue-600 text-white hover:bg-blue-500 transition-colors"
            >
              {showAddForm ? 'Close Add Card' : 'Add Card'}
            </button>
          )}
        </div>

        {mode === 'orders' ? (
          <Orders />
        ) : (
          <div className="pb-8 md:pb-12 space-y-6">
            {mode === 'homepage-banners' && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="text-lg md:text-xl mb-4">Homepage Banners</h2>
                <p className="text-xs md:text-sm text-gray-600 mb-4">
                  Add a new banner or replace existing banner image/link. Changes reflect on website homepage banner section.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2 mb-4">
                  <input
                    value={newBannerSrc}
                    onChange={(e) => setNewBannerSrc(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="New banner image URL"
                  />
                  <input
                    type="file"
                    accept="image/*"
                    onChange={(e) => handleAddBannerUpload(e.target.files?.[0] || null)}
                    className="w-full px-3 py-2 border rounded bg-white"
                  />
                  <input
                    value={newBannerLink}
                    onChange={(e) => setNewBannerLink(e.target.value)}
                    className="w-full px-3 py-2 border rounded"
                    placeholder="Banner link (example: /category/chips-namkeen)"
                  />
                  <button type="button" onClick={handleAddBanner} className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-500 md:col-span-3">
                    Add Banner
                  </button>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {homeBanners.map((banner) => (
                    <div key={banner.id} className="border rounded-lg p-3 bg-gray-50">
                      <img src={banner.src} alt="Homepage banner" className="w-full h-28 object-cover rounded mb-2" />
                      <input
                        value={banner.src}
                        onChange={(e) => handleReplaceBannerImage(banner.id, e.target.value)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2"
                        placeholder="Replace banner image URL"
                      />
                      <input
                        type="file"
                        accept="image/*"
                        onChange={(e) => handleReplaceBannerUpload(banner.id, e.target.files?.[0] || null)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2 bg-white"
                      />
                      <input
                        value={banner.link}
                        onChange={(e) => handleReplaceBannerLink(banner.id, e.target.value)}
                        className="w-full px-2 py-1.5 border rounded text-xs md:text-sm mb-2"
                        placeholder="Replace banner link"
                      />
                      <button
                        type="button"
                        onClick={() => handleDeleteBanner(banner.id)}
                        className="w-full px-2 py-1.5 text-xs md:text-sm border border-red-600 text-red-700 rounded hover:bg-red-50"
                      >
                        Delete Banner
                      </button>
                    </div>
                  ))}
                </div>
              </section>
            )}
            {mode === 'group-cards' && showAddForm && (
              <section className="bg-white rounded-xl shadow-md p-4 md:p-6">
                <h2 className="text-lg md:text-xl mb-4">Add New Card</h2>
                <p className="text-xs md:text-sm text-gray-600 mb-4">
                  Fill product details below. This card will be added in the selected group and category section.
                </p>
                <div className="space-y-2">
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Product Name</label>
                  <input value={String(addDraft.name || '')} onChange={(e) => updateAddDraft('name', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Product Name" />
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Description</label>
                  <textarea value={String(addDraft.description || '')} onChange={(e) => updateAddDraft('description', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Description" rows={3} />
                  <button
                    type="button"
                    onClick={() =>
                      setAddDraft((prev) => ({
                        ...prev,
                        description: autoGenerateDescription(String(prev.name || ''), String(prev.group || ''), String(prev.category || ''))
                      }))
                    }
                    className="text-xs md:text-sm text-blue-700 hover:underline"
                  >
                    Auto Generate Description
                  </button>
                  <label className="block text-[11px] md:text-xs font-medium text-gray-700">Upload Image</label>
                  <input type="file" accept="image/*" onChange={(e) => handleAddImageUpload(e.target.files?.[0] || null)} className="w-full px-3 py-2 border rounded bg-white" />
                  <p className="text-[11px] md:text-xs text-gray-500">Or paste image URL</p>
                  <input value={String(addDraft.image || '')} onChange={(e) => updateAddDraft('image', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Or paste image URL" />
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Group</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Category</label>
                    <select value={String(addDraft.group || '')} onChange={(e) => updateAddDraft('group', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {groupOptions.map((group) => (
                        <option key={group} value={group}>{group}</option>
                      ))}
                    </select>
                    <select value={String(addDraft.category || '')} onChange={(e) => updateAddDraft('category', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {(categoriesByGroup[String(addDraft.group || '')] || []).map((category) => (
                        <option key={category} value={category}>{category}</option>
                      ))}
                    </select>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Sold Qty</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Order Count</label>
                    <input type="number" value={String(addDraft.quantitySold || 0)} onChange={(e) => updateAddDraft('quantitySold', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Sold Qty" />
                    <input type="number" value={String(addDraft.orderCount || 0)} onChange={(e) => updateAddDraft('orderCount', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Order Count" />
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Price (₹)</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Stock</label>
                    <input type="number" step="0.01" value={String(addDraft.price || 0)} onChange={(e) => updateAddDraft('price', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Price (₹)" />
                    <input type="number" value={String(addDraft.stock || 0)} onChange={(e) => updateAddDraft('stock', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="Stock" />
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit Value</label>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit</label>
                    <input type="number" min="0" step="0.01" value={String(addDraft.unitValue || 1)} onChange={(e) => updateAddDraft('unitValue', e.target.value)} className="w-full px-3 py-2 border rounded" placeholder="500" />
                    <select value={String(addDraft.unit || 'pcs')} onChange={(e) => updateAddDraft('unit', e.target.value)} className="w-full px-3 py-2 border rounded bg-white">
                      {unitOptions.map((unit) => (
                        <option key={unit} value={unit}>{unit}</option>
                      ))}
                    </select>
                    <p className="text-[11px] md:text-xs text-gray-500 col-span-2">Preview: {String(addDraft.unitValue || 1)} {String(addDraft.unit || 'pcs')}</p>
                    <label className="text-[11px] md:text-xs font-medium text-gray-700 col-span-2">Revenue (₹)</label>
                    <input type="number" step="0.01" value={String(addDraft.revenue || 0)} onChange={(e) => updateAddDraft('revenue', e.target.value)} className="w-full px-3 py-2 border rounded col-span-2" placeholder="Revenue (₹)" />
                  </div>
                  <button type="button" onClick={handleAddCardSave} className="px-4 py-2 bg-green-600 text-yellow-100 rounded hover:bg-green-500">Save New Card</button>
                </div>
              </section>
            )}
            {mode === 'group-cards' && (Object.keys(groupedCards).length === 0 ? (
              <div className="bg-white rounded-xl shadow-md p-8 text-center text-gray-600">
                No products found from orders yet.
              </div>
            ) : (
              Object.entries(groupedCards).map(([groupName, cards]) => (
                <section key={groupName} className="bg-white rounded-xl shadow-md p-4 md:p-6">
                  <h2 className="text-lg md:text-2xl mb-4">{groupName}</h2>
                  {Object.entries(
                    cards.reduce<Record<string, GroupProductCard[]>>((acc, card) => {
                      if (!acc[card.category]) acc[card.category] = [];
                      acc[card.category].push(card);
                      return acc;
                    }, {})
                  ).map(([categoryName, categoryCards]) => (
                    <div key={categoryName} className="mb-5 last:mb-0">
                      <h3 className="text-sm md:text-lg mb-3 capitalize text-gray-800">
                        {categoryName.replace(/-/g, ' ')}
                      </h3>
                      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                        {categoryCards.map((card) => (
                          <article key={card.productId} className="border rounded-lg p-3 bg-gray-50">
                            <img
                              src={editingCardId === card.productId && draftEdit.image ? String(draftEdit.image) : card.image}
                              alt={card.name}
                              className="w-full h-32 object-cover rounded-md mb-3"
                            />
                            <h4 className="text-sm md:text-base mb-2 line-clamp-2">{card.name}</h4>
                            <div className="text-xs md:text-sm text-gray-700 space-y-1">
                              <p><strong>Sold Qty:</strong> {card.quantitySold}</p>
                              <p><strong>Order Count:</strong> {card.orderCount}</p>
                              <p><strong>Price:</strong> ₹{card.price.toFixed(2)}</p>
                              <p><strong>Stock:</strong> {card.stock}</p>
                              <p><strong>Unit:</strong> {card.unitValue ?? 1} {card.unit || 'pcs'}</p>
                              <p><strong>Revenue:</strong> ₹{card.revenue.toFixed(2)}</p>
                            </div>
                            {editingCardId === card.productId ? (
                              <div className="mt-3 border-t pt-3 space-y-2">
                                <p className="text-[11px] md:text-xs text-gray-500">
                                  Edit product details below. You can upload image from your device.
                                </p>
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Product Name</label>
                                <input
                                  value={String(draftEdit.name ?? '')}
                                  onChange={(e) => updateDraft('name', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Product name"
                                />
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Description</label>
                                <textarea
                                  value={String(draftEdit.description ?? '')}
                                  onChange={(e) => updateDraft('description', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Product description"
                                  rows={3}
                                />
                                <label className="block text-[11px] md:text-xs font-medium text-gray-700">Upload Image</label>
                                <input
                                  type="file"
                                  accept="image/*"
                                  onChange={(e) => handleImageUpload(e.target.files?.[0] || null)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                />
                                <p className="text-[11px] md:text-xs text-gray-500">Or paste an image URL</p>
                                <input
                                  value={String(draftEdit.image ?? '')}
                                  onChange={(e) => updateDraft('image', e.target.value)}
                                  className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                  placeholder="Image URL (add/change image)"
                                />
                                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Group</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Category</label>
                                  <select
                                    value={String(draftEdit.group ?? '')}
                                    onChange={(e) => updateDraft('group', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {groupOptions.map((group) => (
                                      <option key={group} value={group}>{group}</option>
                                    ))}
                                  </select>
                                  <select
                                    value={String(draftEdit.category ?? '')}
                                    onChange={(e) => updateDraft('category', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {(categoriesByGroup[String(draftEdit.group ?? '')] || []).map((category) => (
                                      <option key={category} value={category}>{category}</option>
                                    ))}
                                  </select>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Sold Qty</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Order Count</label>
                                  <input
                                    type="number"
                                    value={String(draftEdit.quantitySold ?? 0)}
                                    onChange={(e) => updateDraft('quantitySold', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Sold Qty"
                                  />
                                  <input
                                    type="number"
                                    value={String(draftEdit.orderCount ?? 0)}
                                    onChange={(e) => updateDraft('orderCount', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Order Count"
                                  />
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Price (₹)</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Stock</label>
                                  <input
                                    type="number"
                                    step="0.01"
                                    value={String(draftEdit.price ?? 0)}
                                    onChange={(e) => updateDraft('price', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Price"
                                  />
                                  <input
                                    type="number"
                                    value={String(draftEdit.stock ?? 0)}
                                    onChange={(e) => updateDraft('stock', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="Stock"
                                  />
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit Value</label>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700">Unit</label>
                                  <input
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={String(draftEdit.unitValue ?? 1)}
                                    onChange={(e) => updateDraft('unitValue', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm"
                                    placeholder="500"
                                  />
                                  <select
                                    value={String(draftEdit.unit ?? 'pcs')}
                                    onChange={(e) => updateDraft('unit', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm bg-white"
                                  >
                                    {unitOptions.map((unit) => (
                                      <option key={unit} value={unit}>{unit}</option>
                                    ))}
                                  </select>
                                  <p className="text-[11px] md:text-xs text-gray-500 col-span-2">Preview: {String(draftEdit.unitValue ?? 1)} {String(draftEdit.unit ?? 'pcs')}</p>
                                  <label className="text-[11px] md:text-xs font-medium text-gray-700 col-span-2">Revenue (₹)</label>
                                  <input
                                    type="number"
                                    step="0.01"
                                    value={String(draftEdit.revenue ?? 0)}
                                    onChange={(e) => updateDraft('revenue', e.target.value)}
                                    className="w-full px-2 py-1.5 border rounded text-xs md:text-sm col-span-2"
                                    placeholder="Revenue"
                                  />
                                </div>
                                <div className="flex flex-col sm:flex-row gap-2">
                                  <button
                                    type="button"
                                    onClick={() => saveEditing(card.productId)}
                                    className="flex-1 px-2 py-1.5 text-xs md:text-sm bg-green-600 text-yellow-100 rounded hover:bg-green-500"
                                  >
                                    Save
                                  </button>
                                  <button
                                    type="button"
                                    onClick={cancelEditing}
                                    className="flex-1 px-2 py-1.5 text-xs md:text-sm border rounded hover:bg-gray-100"
                                  >
                                    Cancel
                                  </button>
                                </div>
                              </div>
                            ) : (
                              <div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-2">
                                <button
                                  type="button"
                                  onClick={() => startEditing(card)}
                                  className="w-full px-2 py-1.5 text-xs md:text-sm border border-green-600 text-green-700 rounded hover:bg-green-50"
                                >
                                  Edit Card
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleDeleteCard(card)}
                                  className="w-full px-2 py-1.5 text-xs md:text-sm border border-red-600 text-red-700 rounded hover:bg-red-50"
                                >
                                  Delete Card
                                </button>
                              </div>
                            )}
                          </article>
                        ))}
                      </div>
                    </div>
                  ))}
                </section>
              ))
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
